### ISSUE TITLE
请问R619AC的支持是64M还是128M，谢谢

### ISSUE THREAD

**Issue by zcracker** [Richard-Tung/openwrt#1]
Device p2w,r619ac-128m not supported by this image Supported devices: p2w,r619ac Image check failed.

**Comment by zcracker** [comment]
编译的R619AC固件在opboot下刷机也无法启动

**Comment by Richard-Tung** [comment]
64m固件 原版uboot正常启动

**Comment by zcracker** [comment]
是否可以支持128m固件 谢谢
